### PR TITLE
Angular 11 update

### PR DESCRIPTION
**Pull request by kyle-n**
Updates dependencies for test project to Angular 11

### CODE REVIEW

**Comment by tehfedaykin** [comment]
Awesome! Did you run code/unit tests? I think we're likely using the deprecated syntax for unit tests that will need to be fixed.

**Comment by kyle-n** [comment]
👍  Unit and e2e tests pass. I also removed the deprecated `async()` from `@angular/core/testing` from tests.

@tehfedaykin

**Comment by tehfedaykin** [comment]
ok. a few other requests while looking at this:

1. can we update to strict mode and make changes necessary? (I'm assuming there will be mostly template-typechecking issues as we update the template vs. component file differently across steps. 
2. can we migrate to ESLint?

**Review by tehfedaykin — APPROVED** [review]

**Comment by kyle-n** [comment]
Closing this to do one for Angular 12 instead

**Pull request closed without merging**
